---
title: "LandTrendr-Paramo - GABAM"
author: "James Millington"
date: "2021-09-01"
output: 
  github_document:
    toc: true
---


```{r warning=F, message=F}
library(raster)
library(sf)
library(tidyverse)
```

Load GABAM raster
```{r}

gabam <- raster("Data/GABAM/N10W080_2012.TIF")

paramo_2deg_ext <- extent(-74, -72, 5, 7) 

gabam_crop <- crop(gabam,paramo_2deg_ext)
gabam_crop <- projectRaster(gabam_crop, crs="+proj=utm +zone=18 +datum=WGS84 +units=m +no_defs")

GISpath <- "Data/Fire GIS Files/" 
buf <- st_read(paste0(GISpath,"500mbufferOfComplejos/GroundTruthingBuffer500m.shp"))
buf <- st_transform(buf, "+proj=utm +zone=18 +datum=WGS84 +units=m +no_defs")

plot(dem)
plot(st_geometry(buf), add=T)

demll <- projectRaster(dem, crs="+proj=longlat +datum=WGS84 +no_defs", method='ngb')

```


```{r}

    #MEMORY MANAGEMENT see https://r-forge.r-project.org/forum/forum.php?thread_id=30946&forum_id=995&group_id=302
    raster_tmp_dir <- "/r_raster_tmp"  ## define the name of a temp directory where raster tmp files will be stored
    dir.create(raster_tmp_dir, showWarnings = F, recursive = T)  ## create the directory
    rasterOptions(tmpdir = raster_tmp_dir,
                  memfrac=0.3)  ## set raster options

paramo_2deg_ext <- extent(-74, -72, 5, 7)
#yr <- 2012
gabam_stk <- stack()
years <- 2012:2016
for(yr in years){
  print(paste0(yr))
  gabam_ras  <- raster(paste0("Data/GABAM/N10W080_",yr,".TIF"))
  print("read")
  gabam_ras  <- crop(gabam_ras,paramo_2deg_ext)
  print("cropped")
  print(gabam_ras)
  gabam_ras <- subs(gabam_ras, data.frame(from=1,to=yr))
  print("subbed")
  writeRaster(gabam_ras, paste0("Data/GABAM/N10W080_",yr,"_crp.TIF"))
  print("written")
  #gabam_stk <- stack(gabam_stk, gabam_ras_crp)
  #rm(gabam_ras,gabam_ras_crp)
}
```

```{r}

gabam_stk_crp <- stack()
years <- 2012:2016
for(yr in years){
  
  gabam_ras  <- raster(paste0("Data/GABAM/N10W080_",yr,"_crp.TIF"))
  gabam_stk_crp <- stack(gabam_stk_crp, gabam_ras)
  rm(gabam_ras)
}

gabam_stk_crp_utm <- projectRaster(gabam_stk_crp, crs="+proj=utm +zone=18 +datum=WGS84 +units=m +no_defs", method='ngb')

writeRaster(gabam_stk_crp_utm, paste0("Data/GABAM/gabam_stk_utm.TIF"))

rm(gabam_stk_crp)

dem<- raster('Data/SRTM/srtm_ltr.tif')
elevize <- function(x) { ifelse(x < 2000, NA, x) }
dem2000 <- calc(dem, elevize)

gabam_stk_crp_utm <- crop(gabam_stk_crp_utm, extent(dem2000))
writeRaster(gabam_stk_crp_utm, paste0("Data/GABAM/gabam_stk_utm_dem.TIF"))
gabam_stk_crp_utm <- resample(gabam_stk_crp_utm, dem2000)
writeRaster(gabam_stk_crp_utm, paste0("Data/GABAM/gabam_stk_utm_resp.TIF"))
gabam_stk_elev2000 <- mask(gabam_stk_crp_utm, dem2000)
writeRaster(gabam_stk_elev2000, paste0("Data/GABAM/gabam_stk_utm_mask.TIF"))

unNAize <- function(x) { ifelse(is.na(x), 0, x) }
gabam_stk_elev2000_z <- calc(gabam_stk_elev2000,unNAize)

gabam_max <- overlay(gabam_stk_elev2000_z, fun=max)
gabam_sum <- overlay(gabam_stk_elev2000_z, fun=sum)

NAize <- function(x) { ifelse(x == 0, NA, x) }
gabam_max <- calc(gabam_max, NAize)
gabam_sum <- calc(gabam_sum, NAize)

writeRaster(gabam_max, "Data/NBRanalysis/gabam_max_utm.grd", overwrite=TRUE)
writeRaster(gabam_sum, "Data/NBRanalysis/gabam_sum_utm.grd", overwrite=TRUE)

plot(gabam_max)

```


```{r}

gfa_max <- raster("Data/NBRanalysis/gfa_max_utm.grd")
gabam_max <- raster("Data/NBRanalysis/gabam_max_utm.grd")

print(paste0("gfa_max and gabam_max rasters are comparable: ",compareRaster(gfa_max,gabam_max)))

matches <- gfa_max == gabam_max

ct <- crosstab(matches,gfa_max)  #misses are 0s, hits are 1s

#get false alarms [count(dat) - (hits + misses)]
hm <- colSums(ct) #hits+misses
fdat <- freq(gabam_max) #counts
fdat <- fdat[1:5,2] #get counts for 2012:2016

fa <- fdat - hm     #false alarms

propHM <- round(ct[2,] / hm,4)
propHF <- round(ct[2,] / fa,4)

out <- rbind(ct,fa,propHM,propHF)  #bind to table

row.names(out) <- c("misses","hits","F-alarms","propHM","propHF") #set row.names

write.csv(out, paste0("Data/GABAM/PixelOverlap_gabam.csv"))

```




```{r}

gabam_max <- raster("Data/NBRanalysis/gabam_max_utm.grd")

#scenario <- 2
#grp <- "JanApr"
scenario_list <- seq(from=1,to=144,by=1)
#scenario_list <- c(95,2)

for(scenario in scenario_list){
  
  for(grp in c("JanApr","AllYear")){

    print(paste0(grp,"_",scenario))
    
    #MEMORY MANAGEMENT see https://r-forge.r-project.org/forum/forum.php?thread_id=30946&forum_id=995&group_id=302
    raster_tmp_dir <- "/r_raster_tmp"  ## define the name of a temp directory where raster tmp files will be stored
    dir.create(raster_tmp_dir, showWarnings = F, recursive = T)  ## create the directory
    rasterOptions(tmpdir = raster_tmp_dir)  ## set raster options
    
    
    dat <- stack(paste0("Data/NBRanalysis/LTR_",grp,"_",scenario,".tif"))
    dat <- dat[[1]]  #layer 1 is year
    

    print(paste0("dat and gabam_max rasters are comparable: ",compareRaster(gabam_max,dat)))
    
    matches <- gabam_max == dat
    #matches1 <- gfa_max == dat + 1
    
    ct <- crosstab(matches,gabam_max)  #misses are 0s, hits are 1s
    #ct1 <- crosstab(matches1,gfa_max)  #misses are 0s, hits are 1s
    
    #get false alarms [count(dat) - (hits + misses)]
    hm <- colSums(ct) #hits+misses
    fdat <- freq(dat) #counts
    fdat <- fdat[2:6,2] #get counts for 2012:2016
    
    fa <- fdat - hm     #false alarms
    ct <- rbind(ct,fa)  #bind to table
    row.names(ct) <- c("misses","hits","F-alarms") #set row.names
    
    write.csv(ct, paste0("Data/GABAM/PixelOverlap_",grp,"_",scenario,"gabam.csv"))
    
    #remember to delete the temp raster later!  for example
    unlink(raster_tmp_dir, recursive = T, force = T)

  }
}

```


Collate counts and proportions (also calc props) from individual files per pset into combined files for plotting 
```{r, collate}


#scenario <- 1
#grp <- "JanApr"
#scenario_list <- c(1,95)

scenario_list <- seq(from=1,to=144,by=1)

counts_tbl <- tibble(
  year=character(),
  pset=numeric(),
  grp=character(),
  hits=numeric(),
  misses=numeric(),
  falarms=numeric()
)

props_tbl <- tibble(
  year=character(),
  pset=numeric(),
  grp=character(),
  propHM=numeric(),
  propHF=numeric()
)

for(scenario in scenario_list){
  
  for(grp in c("JanApr","AllYear")){
    
    po <- read_csv(paste0("Data/GABAM/PixelOverlap_",grp,"_",scenario,"gabam.csv"), 
                   col_select=-1, 
                   col_types=cols(.default="i"))

    misses <- po %>% 
      slice(1) %>%
      pivot_longer(cols=everything(), names_to="year",values_to="misses")
    
    hits <- po %>% 
      slice(2) %>%
      pivot_longer(cols=everything(), names_to="year",values_to="hits")
      
    falarm <- po %>% 
      slice(3) %>%
      pivot_longer(cols=everything(), names_to="year",values_to="falarms")
    
    counts <- inner_join(hits,misses,by="year")
    counts <- inner_join(counts,falarm,by="year")
    counts <- mutate(counts, pset=scenario,grp=grp)
    counts_tbl <- bind_rows(counts_tbl, counts)
    
    #proportion of hits to misses
    propHM <- round(po[2,]/po[1,],5)
    propHM <-pivot_longer(propHM, cols=everything(), names_to="year",values_to="propHM")
    
    #proportion of hits to false alarms
    propHF <- round(po[2,]/po[3,],5)
    propHF <-pivot_longer(propHF, cols=everything(), names_to="year",values_to="propHF")
    
    props <- inner_join(propHM,propHF,by="year")
    props <- mutate(props, pset=scenario,grp=grp)
    props_tbl <- bind_rows(props_tbl, props)
  }
}

write_csv(counts_tbl, "Data/GABAM/PixelOverlap_Counts-gabam.csv")
write_csv(props_tbl, "Data/GABAM/PixelOverlap_Props-gabam.csv")


```


Function to plot bar charts of counts of hits, misses, FA 
```{r}

plotCounts <- function(.dat, .var){

  #.dat=countsDat
  #.var="misses"
  
  maxcount <- .dat %>%
    select(year:grp, {{.var}}) %>%
    group_by(pset, grp) %>%
    summarise(counts = sum(.data[[.var]])) 
    
  maxcount <- ceiling(max(maxcount$counts))
  
  #for loop across parameter sets (to split plots for legibility)
  Pset_filter <- data.frame(rbind(c(0,24),c(24,48),c(48,72),c(72,96),c(96,120),c(120,144)))
  
  #row=1
  #loop over pset groups and plot
  for(row in 1:length(Pset_filter[,1])){
    
    lower <- Pset_filter[row,1]
    upper <- Pset_filter[row,2]
  
    plotDat <- .dat %>%
      select(year:grp, {{.var}}) %>%
      filter(pset > lower & pset <= upper) %>%
      mutate(pset = formatC(pset, width = 3, format = "d", flag = "0")) %>%  #pad with preceeding 0s so that plots margins are identical
      mutate(pset = factor(pset)) %>%
      mutate(year = factor(year))
  
    p <- ggplot(plotDat, aes(fill=year, y=.data[[.var]], x=grp)) + 
      geom_bar(position="stack", stat="identity") +
      facet_grid(.~pset) +
      ylim(0,maxcount) +
      labs(title=.var) + 
      theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
  
    print(p)
  }
}

```


Run the counts plotting (output to pdf)
```{r, run-count-plots}

countsDat <- read_csv(paste0("Data/GABAM/PixelOverlap_Counts-gabam.csv"))

pdf("Data/GABAM/Hits_PixelOverlap-gabam.pdf", width=10, height=10)
plotCounts(countsDat, "hits")
dev.off()

pdf("Data/GABAM/Misses_PixelOverlap-gabam.pdf", width=10, height=10)
plotCounts(countsDat, "misses")
dev.off()

pdf("Data/GABAM/FAlarms_PixelOverlap-gabam.pdf", width=10, height=10)
plotCounts(countsDat, "falarms")
dev.off()

```

Function to plot bar charts of 
- proportion of hits to misses
- proportion of hits to false alarms
```{r}

plotProps <- function(.dat, .var){

  #.dat=propsDat
  #.var="propHM"
  
  #for loop across parameter sets (to split plots for legibility)
  Pset_filter <- data.frame(rbind(c(0,24),c(24,48),c(48,72),c(72,96),c(96,120),c(120,144)))
  #row <- 1
  #loop over pset groups and plot
  for(row in 1:length(Pset_filter[,1])){
    
    lower <- Pset_filter[row,1]
    upper <- Pset_filter[row,2]
  
    plotDat <- .dat %>%
      select(year:grp, {{.var}}) %>%
      filter(pset > lower & pset <= upper) %>%
      mutate(pset = formatC(pset, width = 3, format = "d", flag = "0")) %>%  #pad with preceeding 0s so that plots margins are identical
      mutate(pset = factor(pset)) %>%
      mutate(year = factor(year)) 
  
    p <- ggplot(plotDat, aes(fill=year, y=.data[[.var]], x=grp)) + 
      geom_bar(position="dodge",stat="identity") +
      facet_grid(.~pset) +
      ylim(0,0.1) +
      labs(title=.var) + 
      theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
  
    print(p)
  }
}

```

Run the proportions plotting (output to pdf)
```{r, run-props-plots}
propsDat <- read_csv(paste0("Data/GABAM/PixelOverlap_Props-gabam.csv"))

pdf("Data/GABAM/PropHM_PixelOverlap-gabam.pdf", width=10, height=10)
plotProps(propsDat, "propHM")
dev.off()

pdf("Data/GABAM/PropHF_PixelOverlap-gabam.pdf", width=10, height=10)
plotProps(propsDat, "propHF")
dev.off()

```

