---
title: "LandTrendr-Paramo - Global Fire Atlas"
author: "James Millington"
date: "2021-07-30"
output: 
  github_document:
    toc: true
---


```{r warning=F, message=F}
library(raster)
library(sf)
library(dplyr)

paramo_2deg_ext <- extent(-74, -72, 5, 7)

dem <- raster('/home/james/wdResearch/LandTrendr-Paramo/Data/SRTM/srtm_22_11/srtm_22_11.tif')
dem <- crop(dem, paramo_2deg_ext)

years <- 2011:2016

for(yr in years){
  point <- st_read(paste0("Data/MODIS/Global_Fire_Atlas/Global_fire_atlas_V1_ignitions_",yr,"/Global_fire_atlas_V1_ignitions_",yr,".shp"))
  point <- st_crop(point, paramo_2deg_ext)
  
  perim  <- st_read(paste0("Data/MODIS/Global_Fire_Atlas/Global_fire_atlas_V1_perimeter_",yr,"/Global_fire_atlas_V1_perimeter_",yr,".shp"))
  perim <- st_crop(perim, paramo_2deg_ext)
  
  point_dem <- extract(dem, point, sp=TRUE)
  perim_dem <- extract(dem, perim, fun=min, sp=TRUE)
  
  st_write(st_as_sf(point_dem), paste0("Data/MODIS/Global_Fire_Atlas/",yr,"/GFA_ignitions_elev_",yr,".shp"))
  st_write(st_as_sf(perim_dem), paste0("Data/MODIS/Global_Fire_Atlas/",yr,"/GFA_perimeter_elev_",yr,".shp"))
}
```

```{r}
y <- 2016
dta  <- st_read(paste0("Data/MODIS/Global_Fire_Atlas/",y,"/GFA_ignitions_elev_",y,".shp"))

plot(dem)
plot(dta['s_22_11'], pch=3,color='blue',add=T)
plot(st_geometry(buf),border='red',add=T)

```





Load landsat raster  [change this to use SRTM DEM to decide study area]
```{r}
dat1 <- raster("Data/ClearImages/ClearJan0.tif")
```

Create polygon of our max study extent
```{r}
bb <- bbox(dat1)

#following from https://gis.stackexchange.com/a/403979
bb_pol = st_polygon(
  list(
    cbind(
      bb[1,][c(1,2,2,1,1)], 
      bb[2,][c(1,1,2,2,1)])
  )
)

#set projection to original raster (dat1)
bb_pol = st_sfc(bb_pol, crs="+proj=utm +zone=18 +datum=WGS84 +units=m +no_defs +ellps=WGS84 +towgs84=0,0,0")
#reproject to GFA raster
bb_pol <- st_transform(bb_pol, "+proj=longlat +datum=WGS84 +no_defs")
```

Clip points to bounding box
```{r}

#i16_p <- st_intersection(i16, bb_pol)
#plot(i16_p)

p16_p <- st_intersection(p16, bb_pol)
plot(p16_p)

```

Load paramo boundary shapefile
```{r results = 'hide', warning=F, message=F}
GISpath <- "/home/james/OneDrive/Research/Projects/ColombiaBIO/Fire/Fire GIS Files/" #linux
buf <- st_read(paste0(GISpath,"500mbufferOfComplejos/GroundTruthingBuffer500m.shp"))

#set crs of shp to same as for cci raster
buf <- st_transform(buf, "+proj=longlat +datum=WGS84 +no_defs")
```


```{r}

plot(st_geometry(p16_p),col='black',pch=3)
plot(st_geometry(buf),border='red',add=T)

```

Next Steps
- Combined all GFA years?
- Filter LTR data by size (min 21 ha)?

```{r}
#function to set 0 to NA in raster
NAize <- function(x) { ifelse(x == 0, NA, x) }

#function to set 0 to NA in stack
myStack_NAize <- function(myStack){
  yr <- calc(myStack[[1]],NAize)
  myStack <- mask(myStack, yr)
  return(myStack)
}
```

```{r}

stk <- stack('/home/james/wdResearch/LandTrendr-Paramo/Data/NBRanalysis/LTR_JanApr_96.tif')
stk <- myStack_NAize(stk)

ras <- stk[[1]]
ras <- projectRaster(ras, crs="+proj=longlat +datum=WGS84 +no_defs")
crs(ras)
summary(ras)
plot(stk)
```

```{r}

plot(ras)
plot(st_geometry(p16_p),col='black',pch=3,add=T)
plot(st_geometry(buf),border='red',add=T)

```